---
automation:
config:
frontend:
history:
logbook:
map:
mobile_app:
person:
sun:
system_health:
zeroconf:
wake_on_lan:

tts:
  - platform: google_translate

recorder:
  db_url: !env_var RECORDER_DB_URL
  auto_purge: false
  purge_keep_days: 365
  exclude:
    domains:
      - automation
      - updater

# mqtt:
#   broker: mosquitto.mosquitto.svc.cluster.local
#   discovery: true
#   protocol: "3.1.1"
#   port: 1883
#   username: !env_var MQTT_USERNAME
#   password: !env_var MQTT_PASSWORD
#   birth_message:
#     topic: 'hass/status'
#     payload: 'online'
#   will_message:
#     topic: 'hass/status'
#     payload: 'offline'
