---
automation:
config:
frontend:
history:
logbook:
map:
mobile_app:
person:
sun:
system_health:
zeroconf:
wake_on_lan:
api:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.0.0/16
    - 172.31.0.0/16

tts:
  - platform: google_translate

homeassistant:
  name: Home
  latitude: !env_var HASS_LATITUDE
  longitude: !env_var HASS_LONGITUDE
  elevation: 0
  unit_system: metric
  currency: GBP
  country: GB
  time_zone: Europe/London
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.*_update_available":
      hidden: true
    "sensor.*_linkquality":
      hidden: true

template:
  - sensor:
      - name: "Average temperature"
        unit_of_measurement: "°C"
        state: >
          {% set bedroom = states('sensor.bedroom_climate_temperature') | float %}
          {% set lounge = states('sensor.lounge_climate_temperature') | float %}
          {% set office = states('sensor.office_climate_temperature') | float %}
          {% set bathroom = states('sensor.bathroom_climate_temperature') | float %}

          {{ ((bedroom + lounge + office + bathroom) / 4) | round(1, default=0) }}

homekit:
  filter:
    exclude_domains:
      - device_tracker
    exclude_entities: !include hidden-entities.yaml

alexa:
  smart_home:
    locale: en-GB
    endpoint: https://api.eu.amazonalexa.com/v3/events
    client_id: !env_var ALEXA_CLIENT_ID
    client_secret: !env_var ALEXA_CLIENT_SECRET
    filter:
      exclude_entities: !include hidden-entities.yaml
    entity_config:
      cover.office_blinds:
        display_categories: INTERIOR_BLIND
      switch.bathroom_fan:
        display_categories: FAN
      switch.en_suite_fan:
        display_categories: FAN
      media_player.chromecast:
        display_categories: STREAMING_DEVICE
      switch.plug_1_switch:
        display_categories: SMARTPLUG
      switch.plug_2_switch:
        display_categories: SMARTPLUG
