---
automation:
config:
frontend:
history:
logbook:
map:
mobile_app:
person:
sun:
system_health:
zeroconf:
wake_on_lan:
api:

tts:
  - platform: google_translate

homeassistant:
  name: Home
  latitude: !env_var HASS_LATITUDE
  longitude: !env_var HASS_LONGITUDE
  elevation: 0
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

recorder:
  db_url: !env_var RECORDER_DB_URL
  auto_purge: false
  purge_keep_days: 365
  exclude:
    domains:
      - automation
      - updater

mqtt:
  broker: mosquitto.mosquitto.svc.cluster.local
  discovery: true
  protocol: "3.1.1"
  port: 1883
  username: !env_var MQTT_USERNAME
  password: !env_var MQTT_PASSWORD
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

homekit:
  filter:
    exclude_domains:
      - device_tracker
  entity_config:
    media_player.chromecast:
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute

prometheus:
  component_config_glob:
    sensor.*_hum:
      override_metric: humidity_percent
    sensor.*_temp:
      override_metric: temperature_c
    sensor.temperature*:
      override_metric: temperature_c
    sensor.*_bat:
      override_metric: battery_percent
  filter:
    include_domains:
      - sensor
      - binary_sensor
      - switch
      - device_tracker

alexa:
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret ALEXA_CLIENT_ID
    client_secret: !secret ALEXA_CLIENT_SECRET
