- platform: mqtt
  schema: json
  name: bathroom_lights
  command_topic: "zigbee2mqtt/bathroom_lights/set"
  state_topic: "zigbee2mqtt/bathroom_lights"
  color_temp: true
  brightness: true
- platform: mqtt
  schema: json
  name: ensuite_lights
  command_topic: "zigbee2mqtt/ensuite_lights/set"
  state_topic: "zigbee2mqtt/ensuite_lights"
  color_temp: true
  brightness: true
- platform: mqtt
  schema: json
  name: kitchen_lights
  command_topic: "zigbee2mqtt/kitchen_lights/set"
  state_topic: "zigbee2mqtt/kitchen_lights"
  color_temp: true
  brightness: true
- platform: mqtt
  schema: json
  name: lounge_lights
  command_topic: "zigbee2mqtt/kitchen_lights/set"
  state_topic: "zigbee2mqtt/kitchen_lights"
  color_temp: true
  brightness: true
